1.2.5 engine release
fourieraudio/docs pull request #40
Opened 2024-12-02 09:48 UTC by elliotsinclair

Small update to website as customers are now receiving transform.engines on version 1.2.5.

2024-12-02 10:30 UTC, henryharrod reviewed
I wonder if the best way to do this might be to keep the 'current' engine version as 1.2.1 )(as that's what's availble to download) and add an 'info' or 'note' explaining that some units out of the factory might show a version 1.2.5 - with an explanitory sentance or two?

2024-12-02 11:09 UTC, elliotsinclair commented
Agree! Just added some edits, think that works better?

2024-12-02 11:10 UTC, henryharrod reviewed
I think we can probably just link 1.2.5 to 1.2.1 page and drop the new .md file?

2024-12-02 11:11 UTC, elliotsinclair commented
Done!

2024-12-02 11:20 UTC, henryharrod commented on info/downloads/index.md
> +The latest **transform**.engine's will ship from the factory with Engine Version, 1.2.5. these are purely manufacturing changes, and Engine Version 1.2.1 is still the latest version to download.
```suggestion
The latest **transform**.engines will ship from the factory with Engine Version, 1.2.5. these are purely manufacturing changes, and Engine Version 1.2.1 is still the latest version to download.
```

2024-12-02 11:21 UTC, henryharrod approved these changes
Just one small nitpick - then good to go! Thanks!

2024-12-02 11:21 UTC, henryharrod commented on info/downloads/index.md
> +The latest **transform**.engine's will ship from the factory with Engine Version, 1.2.5. these are purely manufacturing changes, and Engine Version 1.2.1 is still the latest version to download.
Nitpick

2024-12-04 10:55 UTC, henryharrod requested changes

2024-12-04 10:55 UTC, henryharrod commented on info/intro/roadmap.md
> +| FA-598       | Initial console integration - control your plugins from a console! | Q1 2025 |
As per chat message

2024-12-04 11:22 UTC, henryharrod approved these changes

2024-12-04 11:22 UTC, merged